# Generated by Django 3.2.5 on 2021-08-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=30, unique=True, verbose_name='키워드')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='제목')),
                ('contents', models.TextField(verbose_name='내용')),
                ('joindate', models.DateTimeField(auto_now_add=True, verbose_name='본문 생성시간')),
            ],
            options={
                'db_table': 'HT_board',
            },
        ),
    ]
