# Generated by Django 3.2.5 on 2021-08-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeTraining', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ht',
            old_name='joindate',
            new_name='write_date',
        ),
        migrations.AlterField(
            model_name='ht',
            name='part',
            field=models.CharField(max_length=30, verbose_name='키워드'),
        ),
        migrations.AlterField(
            model_name='ht',
            name='title',
            field=models.CharField(max_length=30, verbose_name='제목'),
        ),
    ]
