# Generated by Django 3.2.5 on 2021-08-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeTraining', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ht',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
