# Generated by Django 3.2.5 on 2021-08-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeTraining', '0002_alter_ht_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ht',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
