# Generated by Django 3.2.5 on 2021-08-07 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_email'),
        ('HomeTraining', '0002_auto_20210807_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='ht',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.user', verbose_name='작성자'),
        ),
    ]
