# Generated by Django 3.2.5 on 2021-08-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeTraining', '0003_alter_ht_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ht',
            name='img',
        ),
        migrations.AddField(
            model_name='ht',
            name='images',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
