# Generated by Django 3.2.5 on 2021-08-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeTraining', '0003_ht_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ht',
            name='writer',
            field=models.CharField(max_length=30, null=True, verbose_name='작성자'),
        ),
    ]
