# Generated by Django 3.2.5 on 2021-08-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeTraining', '0004_alter_ht_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ht',
            name='writer',
            field=models.CharField(default=1, max_length=30, verbose_name='작성자'),
            preserve_default=False,
        ),
    ]
