# Generated by Django 3.2.5 on 2021-08-09 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeTraining', '0005_alter_ht_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ht',
            name='writer',
        ),
    ]
