# Generated by Django 3.2.5 on 2021-08-09 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210809_1707'),
        ('HomeTraining', '0007_ht_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ht',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.user', verbose_name='작성자'),
        ),
    ]
