# Generated by Django 3.2.5 on 2021-08-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_class', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='online',
            name='writer',
            field=models.CharField(max_length=30, null=True, verbose_name='작성자'),
        ),
    ]
