# Generated by Django 3.2.5 on 2021-08-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_class', '0002_crolldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crolldata',
            name='link',
            field=models.CharField(max_length=500),
        ),
    ]
