# Generated by Django 3.2.5 on 2021-08-13 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_class', '0002_alter_online_writer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=30, null=True, verbose_name='작성자')),
                ('text', models.CharField(max_length=100, null=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='online_class.online')),
            ],
        ),
    ]
