# Generated by Django 3.2.5 on 2021-08-06 18:02

import account.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=30, unique=True, validators=[account.validation.validate_email], verbose_name='이메일'),
        ),
    ]
