# Generated by Django 3.2.5 on 2021-08-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='닉네임'),
        ),
    ]
