# Generated by Django 3.2.5 on 2021-08-09 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210809_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=30, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='닉네임'),
        ),
    ]
